---
- name: change grub
  hosts: all
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - lineinfile:
        path: /etc/default/grub
        state: present
        regexp: '^GRUB_CMDLINE_LINUX'
        line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
    - name: apply change grub
      shell:
        cmd: grub2-mkconfig -o /etc/default/grub
...

